apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: ragu162004/frontend-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi" 
            limits:
              memory: "512Mi" 
          env:
          - name: VITE_CURRENCY
            valueFrom:
              secretKeyRef:
                name: frontend-secret
                key: VITE_CURRENCY
          - name: VITE_BACKEND_URL
            valueFrom:
              secretKeyRef:
                name: frontend-secret
                key: VITE_BACKEND_URL